### ISSUE TITLE
Not work, stuck after select drive Clover GUI

### ISSUE THREAD

**Issue by indraAsLesmana** [fronttang/Lenovo-ThinkCentre-M720Q-Hackintosh#1]
i have same type m720Q with i7 8700t, B360, always stuck after select drive on Clover GUI.
hope you can help.

Thanks for share.

**Comment by psvajaz** [comment]
Is it possible to make an efi that supports i3 9100t

**Comment by fronttang** [comment]
> i have same type m720Q with i7 8700t, B360, always stuck after select drive on Clover GUI. hope you can help.
> 
> Thanks for share.

Sorry, I no longer maintain this project.

**Comment by fronttang** [comment]
> Is it possible to make an efi that supports i3 9100t

Sorry, I no longer maintain this project.
